name: Deploy to production

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write
  id-token: write

env:
  SLUG: tutorials

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: production
      url: https://ionic.io/docs/${{ env.SLUG }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Build
        run: |
          npm ci --legacy-peer-deps
          npm run build
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::319312831725:role/github-docs
          aws-region: us-east-1
      - name: Deploy
        run: |
          aws s3 sync build/ s3://ionic-docs/production/${{ env.SLUG }}/ --exclude '*.html' --cache-control max-age=31536000 --only-show-errors
          aws s3 sync build/ s3://ionic-docs/production/${{ env.SLUG }}/ --exclude '*' --include '*.html' --cache-control max-age=60 --only-show-errors
